# -*- coding: utf-8 -*-
"""home.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iEdbgFLPFpT46eDiNvkzkpVL1QLMZBc_
"""

import pandas as pd
import streamlit as st
import pickle
from PIL import Image
import numpy as np
df = pd.read_csv('data.csv')

df.head()

df.describe()

ada = pickle.load(open('model.pkl', 'rb'))
st.title('Disorder Predictor')
temp = st.slider('Temperature', 0.0, 43.0, 36.6)
wbc = st.slider('WBC Count', 0.0, 16.0, 7.5)
heart_rate = st.slider('Heart Rate', 0, 50, 140)
age = st.slider('Age', 0, 100, 40)

inputdata  = np.array([temp,wbc,heart_rate,age]).reshape(1,-1)
if st.button('Predict'):
  res = ada.predict(inputdata)[0]
  st.subheader('Results')
  st.write(f"Prediction: {'Not İll' if res == 1 else 'İll'}")

st.subheader('Feature importances: ')
st.image('feature_importance.png')
